
  name: Test Workflow

  on:

    push:

      branches: master




  jobs:

      echo-test:

        name: Echo Test
        runs-on: ubuntu-latest
        steps:

          - name: Execute php output

          run: |
            echo 'Test from PHP Process'
            echo 'test2'

          shell: php

