 
  name: 'Test1 Workflow'

  on:

    push:

      branches: master




  jobs:

      echo-test:

        name: Testing env variables
        runs-on: ubuntu-latest
        steps:

          - name: Sends output

            run: |
                echo "shell used: ${SHELL}";
                echo "user name: ${USERNAME}"

            shell: bash

            env:

              USERNAME: 'Júlio César'

      testing-background:

        name: Testing Background

        runs-on: ubuntu-latest

        steps:

          - name: step1

            shell: bash

            run: |
              sleep 10

            background: true


          - name: step2

            shell: bash

            run: |
              echo 'finished!'
