
  name: 'Test1 Workflow'

  on:

    push:

      branches: master




  jobs:

      echo-test:

        name: Testing env variables
        runs-on: ubuntu-latest
        steps:

          - name: Sends output

            run: |
                echo "shell used: ${SHELL}";
                echo "user name: ${USERNAME}"

            shell: bash

            env:

              USERNAME: 'Júlio César'

      testing-background:

        name: Testing Background

        runs-on: ubuntu-latest

        steps:

          - name: step1

            shell: bash

            run: |
              sleep 10

            background: true


          - name: step2

            shell: bash

            run: |
              echo 'finished!'

      testing-wait-background-steps:

        name: testing waiting for background steps

        runs-on: ubuntu-latest

        steps:

          - name: step1

            shell: bash

            run: |
              sleep 20

            background: true


          - name: step2

            shell: bash

            run: |
              echo 'step2 executed'


          - name: wait step

            wait: [step1]


          - name: step3

            shell: bash

            run: echo step3 executed
