
  name: Test1 Workflow

  on:

    push:

      branches: master




  jobs:

      echo-test:

        name: Echo Test
        runs-on: ubuntu-latest
        steps:

          - name: Sends output

            run: |
                echo "shell used: ${SHELL}";
                echo teste2

            shell: bash

